/*
	Evolutility Model for Model : Object > Nested Collection
	https://github.com/evoluteur/evolutility-models
	(c) 2022 Olivier Giulieri
*/

module.exports = {
  id: "collection",
  world: "designer",
  title: "Collection",
  icon: "/designer/collection.png",
  schema: "evolutility",
  name: "collection",
  namePlural: "collections",
  titleField: "label",
  table: "evol_object_collec",
  position: 40,
  fields: [
    {
      id: "label",
      column: "label",
      label: "Label",
      type: "text",
      maxLength: 200,
      inMany: true,
      width: 62,
      //"required": true,
      inSearch: true,
    },
    {
      id: "cid",
      column: "cid",
      label: "Collection Id",
      type: "text",
      maxLength: 50,
      inMany: true,
      width: 20,
      required: true,
      inSearch: true,
    },
    {
      id: "position",
      column: "position",
      label: "Position",
      type: "integer",
      inMany: true,
      width: 18,
    },
    {
      id: "table",
      column: "table",
      label: "DB Table name",
      type: "text",
      width: 32,
      maxLength: 63,
      required: true,
      inMany: true,
      inSearch: true,
    },
    {
      id: "column",
      column: "dbcolumn",
      label: "DB Column",
      type: "text",
      help: "Column to filter by.",
      width: 30,
      maxLength: 63,
      required: true,
      inMany: true,
      inSearch: true,
    },
    {
      id: "object",
      label: "Object",
      type: "lov",
      object: "object",
      required: true,
      inMany: true,
      noCharts: true,
      width: 38,
      column: "object_id",
      lovTable: "evol_object",
      lovColumn: "title",
      deleteTrigger: true,
    },
    {
      id: "fields",
      label: "Fields",
      type: "json",
      column: "fields",
      required: true,
      width: 100,
      height: 4,
    },
    {
      id: "help",
      column: "help",
      label: "help",
      type: "textmultiline",
      maxLength: 500,
      width: 100,
      height: 4,
      help: "Help tooltip for the Group",
    },
    {
      id: "header",
      column: "header",
      label: "Header",
      type: "textmultiline",
      maxLength: 500,
      width: 100,
      height: 4,
      help: "Introduction text displayed at the top of the group.",
    },
    {
      id: "footer",
      column: "footer",
      label: "Footer",
      type: "textmultiline",
      maxLength: 500,
      width: 100,
      height: 4,
      help: "Footer text displayed below the group.",
    },
    {
      id: "description",
      label: "Description",
      type: "textmultiline",
      column: "description",
      maxLength: 250,
      width: 100,
      height: 3,
      inSearch: true,
    },
  ],
};
