/*
	Evolutility Model for Model/Object
	https://github.com/evoluteur/evolutility-models
	(c) 2022 Olivier Giulieri
*/

module.exports = {
  id: "object",
  world: "designer",
  title: "Objects",
  icon: "/designer/object.png",
  schema: "evolutility",
  name: "object",
  namePlural: "objects",
  titleField: "title",
  table: "evol_object",
  position: 10,
  fields: [
    {
      id: "title",
      column: "title",
      label: "Title",
      help: "example: 'Address book'",
      type: "text",
      maxLength: 200,
      inMany: true,
      inSearch: true,
      width: 82,
      required: true,
    },
    {
      id: "active",
      label: "Active",
      type: "boolean",
      column: "active",
      inMany: true,
      width: 18,
    },
    {
      id: "world",
      type: "lov",
      label: "World",
      width: 62,
      table: "evol_world",
      inMany: true,
      column: "world_id",
      lovTable: "evol_world",
      object: "world",
    },
    {
      id: "noCharts",
      label: "No Charts",
      type: "boolean",
      column: "nocharts",
      width: 35,
    },
    {
      id: "noStats",
      label: "No Stats",
      type: "boolean",
      column: "nostats",
      width: 30,
    },
    {
      id: "table",
      column: "table",
      label: "DB Table name",
      type: "text",
      width: 62,
      maxLength: 63,
      required: true,
      inMany: true,
      inSearch: true,
    },
    // {
    //   id: pkey, // "qid",
    //   column: "pkey",
    //   label: "GraphQL Node ID",
    //   help: "",
    //   type: "text",
    //   width: 38,
    // },
    {
      id: "entity",
      column: "entity",
      label: "Object Id",
      type: "text",
      help: "Unique identifier for the object",
      maxLength: 100,
      required: true,
      inMany: true,
      inSearch: true,
      width: 75,
    },
    {
      id: "name",
      label: "Object name (singular)",
      help: "example: 'contact'",
      type: "text",
      column: "name",
      required: true,
      maxLength: 50,
      inMany: true,
      inSearch: true,
      width: 62,
    },
    {
      id: "namePlural",
      label: "name (plural)",
      help: "example: 'contacts'",
      type: "text",
      column: "nameplural",
      required: true,
      maxLength: 50,
      width: 38,
    },
    {
      id: "icon",
      label: "Icon",
      type: "image",
      column: "icon",
      maxLength: "50",
      width: 35,
      help: "example='contact.gif'",
      readOnly: true,
      inMany: true,
    },

    {
      id: "titleField",
      label: "Title field",
      help: "Id of the field used as record title",
      type: "text",
      column: "titlefield",
      width: 38,
    },
    {
      id: "description",
      label: "Description",
      type: "textmultiline",
      column: "description",
      maxLength: 250,
      width: 100,
      height: 4,
      inSearch: true,
    },
  ],
  groups: [
    {
      id: "p1",
      type: "panel",
      label: "Object",
      width: 62,
      fields: [
        "title",
        "active",
        "name",
        "namePlural",
        "world",
        "table",
        "titleField",
      ],
    },
    {
      id: "p2",
      type: "panel",
      label: "Info",
      width: 38,
      fields: ["entity", "icon", "noCharts", "noStats", "description"],
    },
  ],
  collections: [
    {
      id: "collec-fields",
      table: "evol_field",
      column: "object_id",
      object: "field",
      title: "Fields",
      orderBy: "position, t1.id",
      fields: [
        "fid",
        "label",
        "column",
        "type",
        "inMany",
        "inSearch",
        "required",
      ],
    },
    {
      id: "collec-groups",
      label: "Field groups",
      table: "evol_object_group",
      column: "object_id",
      object: "group",
      orderBy: "position, t1.id",
      fields: ["gid", "label", "type", "fields"],
    },
    {
      id: "collec-collecs",
      table: "evol_object_collec",
      title: "Collections",
      column: "object_id",
      object: "collection",
      orderBy: "position, t1.id",
      fields: ["cid", "label", "column", "object", "fields"],
    },
  ],
};
