/*!
    Evolutility-Models

    Helper functions mostly for writing to files and console.

    https://github.com/evoluteur/evolutility-models
    (c) 2026 Olivier Giulieri
*/

import path from "path";
import fs from "fs";
import type { Model } from "./types.ts";
import pkg from "../package.json" with { type: "json" };
const { version } = pkg;

const github: Record<string, string> = {
  model: "https://github.com/evoluteur/evolutility-models",
  UI: "https://github.com/evoluteur/evolutility-ui-react",
  DB: "https://github.com/evoluteur/evolutility-server-node",
};

const fnError = (err: NodeJS.ErrnoException | null): void => {
  if (err) throw err;
};

const removeDirectory = (nDir: string): void => {
  if (fs.existsSync(nDir)) {
    fs.readdirSync(nDir).forEach((entry) => {
      const entry_path = path.join(nDir, entry);
      if (fs.lstatSync(entry_path).isDirectory()) {
        removeDirectory(entry_path);
      } else {
        fs.unlinkSync(entry_path);
      }
    });
    fs.rmdirSync(nDir);
  }
};

const clearDirectory = (nDir: string): void => {
  removeDirectory(nDir);
  fs.mkdirSync(nDir);
};

const makeDirectory = (nDir: string): void => {
  if (!fs.existsSync(nDir)) {
    fs.mkdirSync(nDir);
  }
};

const logTask = (modelType: string, models: Record<string, unknown>): void => {
  const nbModels = Object.keys(models).length;
  console.log(`Generating ${nbModels} ${modelType}-models:`);
};

const headComment = (
  modelType: string,
  m?: Pick<Model, "label" | "title" | "id">,
): string =>
  `/*\n  ${modelType} model for ${m?.label || m?.title || m?.id} \n` +
  `  Generated by evolutility-models v.${version} at ${new Date().toLocaleString()}\n  ` +
  (github[modelType] ?? "") +
  "\n*/\n\n";

const txtExportModel = (modelType: string, model: Model): string =>
  headComment(modelType, model) +
  "const model = " +
  JSON.stringify(model, null, "\t") +
  "\n\nexport default model;\n";

const writeFile = (filename: string, txt: string): void => {
  console.log("=> " + filename);
  fs.writeFile(filename, txt, fnError);
};

export {
  clearDirectory,
  removeDirectory,
  makeDirectory,
  writeFile,
  logTask,
  headComment,
  txtExportModel,
};
