/*
  Evolutility Model for Address Book
*/

import { FieldType, type Model } from "../../scripts/types.js";

export const contact = {
  id: "contact",
  oid: 2,
  world: "organizer",
  active: true,
  position: 10,
  label: "Address book",
  icon: "contact.png",
  table: "contact",
  name: "contact",
  namePlural: "contacts",
  titleField: "firstname",
  titleFunction: (d: any) => d.firstname + " " + d.lastname,
  noStats: true,
  fields: [
    {
      type: FieldType.text,
      id: "lastname",
      label: "Last name",
      maxLength: 50,
      required: true,
      width: 62,
      inMany: true,
      column: "lastname",
      inSearch: true,
    },
    {
      type: FieldType.text,
      id: "firstname",
      label: "First name",
      maxLength: 50,
      required: true,
      width: 38,
      inMany: true,
      column: "firstname",
      inSearch: true,
    },
    {
      type: FieldType.text,
      id: "jobtitle",
      label: "Title",
      maxLength: 50,
      width: 62,
      column: "jobtitle",
      inSearch: true,
    },
    {
      type: FieldType.text,
      id: "company",
      label: "Company",
      maxLength: 50,
      width: 38,
      inMany: true,
      column: "company",
      inSearch: true,
    },
    {
      type: FieldType.email,
      id: "email",
      label: "email",
      maxLength: 100,
      width: 100,
      column: "email",
      inMany: true,
      inSearch: true,
    },
    {
      type: FieldType.url,
      id: "web",
      label: "web",
      maxLength: 255,
      width: 100,
      column: "web",
    },
    {
      type: FieldType.lov,
      id: "category",
      label: "Category",
      width: 100,
      list: [
        { id: 1, text: "Friends" },
        { id: 2, text: "Family" },
        { id: 3, text: "Work" },
        { id: 4, text: "Meditation" },
        { id: 5, text: "Travel" },
        { id: 6, text: "Business" },
        { id: 7, text: "Sport" },
        { id: 8, text: "Restaurants" },
        { id: 9, text: "Misc." },
      ],
      inMany: true,
      column: "category_id",
      lovTable: "contact_category",
    },
    {
      type: FieldType.text,
      id: "phonework",
      label: "Work Phone",
      maxLength: 20,
      width: 100,
      mini: "1",
      column: "phone",
      inSearch: true,
    },
    {
      type: FieldType.text,
      id: "phonecell",
      label: "Cell.",
      maxLength: 20,
      width: 100,
      mini: "1",
      column: "phonecell",
      inSearch: true,
    },
    {
      type: FieldType.text,
      id: "phonehome",
      label: "Home Phone",
      maxLength: 20,
      width: 100,
      column: "phonehome",
    },
    {
      type: FieldType.text,
      id: "fax",
      label: "Fax",
      maxLength: 20,
      width: 100,
      column: "fax",
    },
    {
      type: FieldType.textmultiline,
      id: "address",
      label: "Address",
      width: 100,
      height: 3,
      column: "address",
    },
    {
      type: FieldType.text,
      id: "city",
      label: "City",
      maxLength: 100,
      width: 62,
      column: "city",
      inSearch: true,
    },
    {
      type: FieldType.text,
      id: "state",
      label: "State",
      width: 23,
      column: "state",
    },
    {
      type: FieldType.text,
      id: "zip",
      label: "Zip",
      maxLength: 12,
      width: 15,
      column: "zip",
    },
    {
      type: FieldType.text,
      id: "country",
      label: "Country",
      maxLength: 60,
      width: 100,
      column: "country",
    },
    {
      type: FieldType.textmultiline,
      id: "notes",
      label: "Notes",
      maxLength: 1000,
      width: 100,
      height: 6,
      column: "notes",
    },
  ],
  groups: [
    {
      type: "panel",
      label: "Identity",
      width: 62,
      fields: ["lastname", "firstname", "jobtitle", "company", "email", "web"],
    },
    {
      type: "panel",
      label: "Contact Info",
      width: 38,
      fields: ["phone", "phonecell", "phonehome", "fax"],
    },
    {
      type: "panel",
      label: "Address",
      width: 62,
      fields: ["address", "city", "state", "zip", "country"],
    },
    {
      type: "panel",
      label: "Misc.",
      width: 38,
      fields: ["category", "notes"],
    },
  ],
} satisfies Model;
